services:
  chroma:
    image: chromadb/chroma:0.4.24
    ports:
      - "8000:8000"
    restart: unless-stopped

  pathfinder:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - chroma
    restart: unless-stopped